### ISSUE TITLE
Trying to build with C++Builder XE: Need Help

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mr-sun/carnamock#9]
```
Dear Author of carnamock,

I'm creating this issue because I don't know how to contact you.

I'm looking for a mocking framework for C++Builder XE.
That's why I try to build carnamock.

Your project carnamock has some external dependencies:
Where can I get CTIP\cppunit-light from?
Where can I get third_part\hamcrest from?

Cheers,
    Tobias
```

Original issue reported on code.google.com by `tobi.all...@gmail.com` on 28 Jul 2015 at 9:32

**Comment by mr-sun** [comment]
Hi. 
1. The "cppunit-light" it's a c++ unit testing framework. This framework was used only as an example for using the "carnamock" (in the tests). You can use carnamock with some other c++ unit testing framework.
2. I have included the "hamcrest" library files into the carnamock, and have resolved all dependencies.
